fix version validation 1

diff --git a/.github/workflows/github-ci.yaml b/.github/workflows/github-ci.yaml
--- a/.github/workflows/github-ci.yaml
+++ b/.github/workflows/github-ci.yaml
@@ -17,54 +17,57 @@ jobs:
       - name: Get Previous Version from Git
         id: previous-version
         run: |
-          if git rev-parse HEAD^ >/dev/null 2>&1; then
-            PREVIOUS_VERSION=$(git show HEAD^:manifest.json | jq -r '.version')
-          else
-            PREVIOUS_VERSION="0.0.0"  # Fallback version if no previous commit exists
-          fi
-          echo "Previous version in manifest.json: $PREVIOUS_VERSION"
-          echo "PREVIOUS_VERSION=$PREVIOUS_VERSION" >> $GITHUB_ENV
+          git show HEAD~1:manifest.json | jq -r '.version' > prev_version.txt
+          echo "Previous version: $(cat prev_version.txt)"
       - name: Get Current Version from manifest.json
         id: current-version
         run: |
           CURRENT_VERSION=$(cat manifest.json | jq -r '.version')
           echo "Current version in manifest.json: $CURRENT_VERSION"
           echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
-      - name: Check Version Update
-        id: check-version
+      - name: Compare manifest versions
         run: |
-          version_gt() {
-            # Compare two versions passed as arguments.
-            # Returns 0 (true) if $1 > $2
-            # Returns 1 (false) otherwise
-            [ "$1" = "$2" ] && return 1
-            local IFS=.
-            local i ver1=($1) ver2=($2)
-            # Fill empty fields in ver1 with zeros
-            for ((i=${#ver1[@]}; i<${#ver2[@]}; i++)); do
-                ver1[i]=0
-            done
-            # Compare version numbers
-            for ((i=0; i<${#ver1[@]}; i++)); do
-                if [[ -z ${ver2[i]} ]]; then
-                    ver2[i]=0
-                fi
-                if ((10#${ver1[i]} > 10#${ver2[i]})); then
-                    return 0
-                fi
-                if ((10#${ver1[i]} < 10#${ver2[i]})); then
-                    return 1
-                fi
-            done
-            return 1
-          }
-
-          if version_gt "$CURRENT_VERSION" "$PREVIOUS_VERSION"; then
-            echo "Version has been updated. Proceeding with publishing."
-          else
-            echo "The version in manifest.json is not greater than the previous version."
+          if [ "$(cat prev_version.txt)" = "$(cat curr_version.txt)" ]; then
+            echo "Version has not increased. Failing the build."
             exit 1
           fi
+          echo "Version has increased. Proceeding with the build."
+
+#      - name: Check Version Update
+#        id: check-version
+#        run: |
+#          version_gt() {
+#            # Compare two versions passed as arguments.
+#            # Returns 0 (true) if $1 > $2
+#            # Returns 1 (false) otherwise
+#            [ "$1" = "$2" ] && return 1
+#            local IFS=.
+#            local i ver1=($1) ver2=($2)
+#            # Fill empty fields in ver1 with zeros
+#            for ((i=${#ver1[@]}; i<${#ver2[@]}; i++)); do
+#                ver1[i]=0
+#            done
+#            # Compare version numbers
+#            for ((i=0; i<${#ver1[@]}; i++)); do
+#                if [[ -z ${ver2[i]} ]]; then
+#                    ver2[i]=0
+#                fi
+#                if ((10#${ver1[i]} > 10#${ver2[i]})); then
+#                    return 0
+#                fi
+#                if ((10#${ver1[i]} < 10#${ver2[i]})); then
+#                    return 1
+#                fi
+#            done
+#            return 1
+#          }
+#
+#          if version_gt "$CURRENT_VERSION" "$PREVIOUS_VERSION"; then
+#            echo "Version has been updated. Proceeding with publishing."
+#          else
+#            echo "The version in manifest.json is not greater than the previous version."
+#            exit 1
+#          fi
 
       - name: Zip Extension
         run: |
